### ISSUE TITLE
Older versions of the container don't seem to support submodules?

### ISSUE THREAD

**Issue by manchicken** [perl-actions/install-with-cpanm#8]
Reference: https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/runs/3785990895?check_suite_focus=true

It looks like submodules aren't supported in older versions, and I’m guessing that this is because `git` is missing from the older versions. Anything older than 5.24 (inclusive) doesn’t seem like it plays nice with submodules, and it looks like that’s just because there’s no `git` executable in `$PATH`.

**Comment by manchicken** [comment]
I suspect this is related to this: https://github.com/Perl/docker-perl-tester/issues/19

**Comment by oalders** [comment]
Closed via https://github.com/Perl/docker-perl-tester/issues/19
